services:
  dev:
    pull_policy: build
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./todo_app
        target: /code/todo_app
  prod:
    pull_policy: build
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 8000:8000
