services:
  test:
    pull_policy: build
    build:
      context: .
      target: test
    env_file:
      - path: .env.test
        required: true
  dev:
    pull_policy: build
    build:
      context: .
      target: development
    env_file:
      - path: ./.env
        required: false
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./todo_app
        target: /code/todo_app
  prod:
    pull_policy: build
    build:
      context: .
      target: production
    env_file:
      - path: ./.env
        required: false
    ports:
      - 8000:8000
